---
title: "Final Project"
author: "Veronica Jenkins, Anika Deshpande, Katie Clayton"
date: "`r Sys.Date()`"
output: html_document  
editor_options: 
  markdown: 
    wrap: 72
---

```{r LoadPackages}

library(dplyr)
library(ggplot2)
library(readxl)
library(tidyverse)
library(readr)
library(tidyr)

TimeSleep <- read_excel("~/Desktop/TimeSleep.xlsx")
SleepQualityData <- read_excel("~/Desktop/SleepQualityData.xlsx")
```

```{r TimeSleep}
#load data 
TimeSleep <- read_excel("~/Desktop/TimeSleep.xlsx")

#rename columns 
colnames(TimeSleep)<- c('Index','Year','Period','AverageHoursPerDaySleeping','Standard Error','Type of Days','Age Group','Activity','Sex')

#Make values in "Average Hours Per Day Sleeping" coloumns 
TimeSleep$`AverageHoursPerDaySleeping`<- as.numeric(TimeSleep$`AverageHoursPerDaySleeping`)

#removes first column 
TimeSleep <- TimeSleep[-1,]
```

```{r SleepQuality}
#rename column names
colnames(SleepQualityData) <- c('Start', 'End', 'SleepQuality', 'Regularity', 'Mood', 'HeartRate(BPM)', 'Steps', 'AlarmMode', 'AirPressure(Pa)', 'City', 'MovementsPerHour', 'TimeInBed(Seconds)', 'TimeAsleep(Seconds)', 'TimeBeforeSleep(Seconds)', 'WindowStart', 'WindowStop', 'DidSnore', 'SnoreTime', 'WeatherTemperature(Celcius)', 'WeatherTypes', 'Notes')

#get rid of the first column
SleepQualityData <- SleepQualityData[-1,]

```

```{r WrangleHoursByAge}
HoursByAge<- TimeSleep%>%
  group_by(`Age Group`)%>%
  summarize(
    Mean=mean(`AverageHoursPerDaySleeping`)
  )
HoursByAge<-HoursByAge[-2,]

```

```{r HoursByAgeVisualization}
# making the visualization for HoursByAge
#load ggplot, dplyr and HoursByAge data
library(scales)
library(ggplot2)
data(HoursByAge)
ggplot(
  data = HoursByAge,
  mapping = aes(x = `Age Group`, weight = Mean)
) +
  geom_bar(fill = "#FFD1E8", width = 0.67, color = "black") +
  # adding titles and labels
  labs(
    x = "Age Group",
    y = "Mean Hours of Sleep",
    title = "Mean Hours of Sleep per Night Depending on Age Group"
  ) +
  theme(axis.line.x = element_line(color="black", size = .25),
        axis.line.y = element_line(color="black", size = .25)
  ) +
  scale_y_continuous(breaks = seq(0,10, by = 0.5), limits = c(0,10), expand = c(0, 0))
```

```{r SleepQualityByHoursTidyData}
#TidyData

#Create a dataframe with only the necessary columns
SleepQuality <- data.frame(SleepQualityData$`Start`, SleepQualityData$`End`, SleepQualityData$`SleepQuality`)
#rename the columns
colnames(SleepQuality) <- c('Start', 'End', 'SleepQuality')

#Create a column calculating the difference in timestamps to get hours of sleep
SleepQuality <- transform(
  SleepQuality, HoursOfSleep= as.numeric(difftime(as.POSIXct(SleepQualityData$`End`), as.POSIXct(SleepQualityData$`Start`)), units = "hours"))

#round hours of sleep
SleepQuality$`HoursOfSleep` <- round(SleepQuality$`HoursOfSleep`, digits = 2)

#Convert sleep quality to numeric
SleepQualityData$`SleepQuality`<- as.numeric(SleepQualityData$`SleepQuality`)

#load a package to convert sleep quality to percent
library(scales)
library(formattable)
SleepQuality$`SleepQuality` <- formattable::percent(SleepQualityData$`SleepQuality`)

#Create a dataframe with the two neccessary columns and rename the columns
SleepQualityByHours<-data.frame(SleepQuality$`HoursOfSleep`, SleepQuality$`SleepQuality`)
colnames(SleepQualityByHours) <- c('HoursOfSleep', 'SleepQualityPercent')

```

```{r SleepQualityByHoursVisualization}
#use ggplot to create a line graph using the data created 
ggplot(
  data = SleepQualityByHours,
  mapping = aes(x = HoursOfSleep, y = SleepQualityPercent)
  ) +
  #customize point size, color, and shape
  geom_point(shape = "circle", size = 1.0, colour = "#BF1B6D") +
  #create a line of best fit and get rid of the spanning color
  geom_smooth(span = 0.75, se = FALSE, colour = "black") +
  #create titles and axis labels
  labs(
    x = "Hours of Sleep",
    y = "Sleep Quality Percent",
    title = "Hours of Sleep Vs. Sleep Quality"
  ) +
  #set the graph appearance and fix scaling issues
  theme_minimal() +
  scale_x_continuous(breaks = seq(0,14, by = 1), limits = c(0,14), expand = c(0, 0))
```

```{r HoursByDayType}
#create an object for filtered data
HoursByDay <- TimeSleep %>%
  #organize all of the same day types together
  group_by(`Type of Days`) %>%
  #select the two columns needed: day type and average hours asleep 
  select(`Type of Days`, `AverageHoursPerDaySleeping`)

```

```{r HoursByDayTypeVisualization}
#use ggplot to create a boxplot
ggplot(
  data = HoursByDay,
  mapping = aes(x = `Type of Days`, y = AverageHoursPerDaySleeping)
  ) +
  #assign a color to fill the box plot
  geom_boxplot(fill = "#FFD1E8") +
  #create titles and axis labels
  labs(
    x = "Day Classification",
    y = "Hours of Sleep",
    title = "Hours of Sleep by Day Classification"
  ) +
  #set graph appearance and fix axis scaling
  theme_minimal() +
  ylim(7.5, 11)
```

```{r HoursByDaySummaryTable}
library(readxl)
library(kableExtra)
library(janitor)
TimeSleep <- read_excel("~/Desktop/TimeSleep.xlsx")
colnames(TimeSleep)<- c('Index','Year','Period','AverageHoursPerDaySleeping','Standard Error','Type of Days','Age Group','Activity','Sex')
TimeSleep$`AverageHoursPerDaySleeping`<- as.numeric(TimeSleep$`AverageHoursPerDaySleeping`)
TimeSleep <- TimeSleep[-1,]
DaysVsSleep <- TimeSleep %>%
  group_by(`Type of Days`) %>%
  select(`Type of Days`, `AverageHoursPerDaySleeping`) %>%
  summarize(
    across(
      .cols = where(is.numeric),
      .fns = list(
        min = ~min(`AverageHoursPerDaySleeping`, na.rm = TRUE),
        Q1 = ~quantile(`AverageHoursPerDaySleeping`, probs = 0.25, na.rm = TRUE),
        median = ~median(`AverageHoursPerDaySleeping`, na.rm = TRUE),
        Q3 = ~quantile(`AverageHoursPerDaySleeping`, probs = 0.75, na.rm = TRUE),
        max = ~max(`AverageHoursPerDaySleeping`, na.rm = TRUE),
        sam = ~mean(`AverageHoursPerDaySleeping`, na.rm = TRUE),
        sasd = ~sd(`AverageHoursPerDaySleeping`, na.rm = TRUE)
      ),
      #round the values to avoid unecessarily large amount of decimal spaces
      round(digits = 2)
    ),
    #get count and format it so that big numbers are separated with commas
    count = format(n(), big.mark = ","),
  )
#rename the columns 
colnames(DaysVsSleep) <- c("Day Classification", "Min", "1st Quartile", "Median", "3rd Quartile", "Max", "Arithmetic Mean", "Arithmetic Standard Deviation", "Count")
#use kable to tidy the table (add caption, add grid, align columns) 
DaysVsSleep %>%
  kable(
    caption = "Statistics on Average Hours Spent Sleeping and Type of Day",
    booktabs = TRUE,
    align = c("l", rep("c", 6))
  ) %>%
  #separate rows through striping the colors
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "condensed"),
    font_size = 16
  ) %>%
  kableExtra::kable_classic()
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
